# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 OKTET Labs Ltd. All rights reserved.

import logging
from typing import ClassVar
import uuid

from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from bublik.data.models.ai_chat_thread import AiChatThread


__all__ = [
    'AiChatFile',
]

logger = logging.getLogger(__name__)


class AiChatFile(models.Model):
    """
    A file generated by the AI chat assistant and kept in the chat file store.

    Ownership derives from the thread: a user may download a file iff they own
    the thread it was generated in. Rows cascade with the thread; the stored
    objects are cleaned up best-effort by the ``pre_delete`` signal below.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text='File identifier (used in the download URL).',
    )
    thread = models.ForeignKey(
        AiChatThread,
        on_delete=models.CASCADE,
        related_name='files',
        help_text='The chat thread the file was generated in.',
    )
    filename = models.CharField(
        max_length=255,
        help_text='Download filename.',
    )
    content_type = models.CharField(
        max_length=127,
        help_text='MIME type served on download.',
    )
    size = models.PositiveIntegerField(
        help_text='Object size in bytes.',
    )
    storage_key = models.CharField(
        max_length=512,
        unique=True,
        help_text='Key in the chat file store (S3 object key, or path on disk).',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        help_text='Timestamp of the file creation.',
    )

    class Meta:
        db_table = 'bublik_ai_chat_file'
        ordering: ClassVar[list] = ['-created']

    def __repr__(self):
        return (
            f'AiChatFile(id={self.id!r}, thread={self.thread_id!r}, '
            f'filename={self.filename!r}, size={self.size!r})'
        )


@receiver(pre_delete, sender=AiChatThread, dispatch_uid='ai_chat_file_storage_cleanup')
def _delete_thread_files(sender, instance, **kwargs):
    """Best-effort cleanup of stored files when a thread is deleted.

    ``pre_delete`` (not ``post_delete``) so the AiChatFile rows still exist and
    threads without files skip the storage round-trip entirely. Failures are
    logged and swallowed: the store being down must not block thread deletion
    (operators on real S3 can use a lifecycle rule on the ``chat/`` prefix
    as a safety net).
    """
    if not instance.files.exists():
        return
    # Lazy: keep the storage backend (and boto3) out of the model-import path
    # (app registry load).
    from bublik.core import ai_chat_storage  # noqa: PLC0415

    try:
        ai_chat_storage.delete_prefix(ai_chat_storage.thread_prefix(instance.pk))
    except Exception:
        logger.warning(
            'failed to delete stored files for chat thread %s',
            instance.pk,
            exc_info=True,
        )
