# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 OKTET Labs Ltd. All rights reserved.

import logging
from typing import ClassVar
import uuid

from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from bublik.data.models.chat_thread import ChatThread


__all__ = [
    'ChatFile',
]

logger = logging.getLogger(__name__)


class ChatFile(models.Model):
    """
    A file generated by the AI chat assistant and stored in S3.

    Ownership derives from the thread: a user may download a file iff they own
    the thread it was generated in. Rows cascade with the thread; the S3
    objects are cleaned up best-effort by the ``pre_delete`` signal below.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text='File identifier (used in the download URL).',
    )
    thread = models.ForeignKey(
        ChatThread,
        on_delete=models.CASCADE,
        related_name='files',
        help_text='The chat thread the file was generated in.',
    )
    filename = models.CharField(
        max_length=255,
        help_text='Download filename.',
    )
    content_type = models.CharField(
        max_length=127,
        help_text='MIME type served on download.',
    )
    size = models.PositiveIntegerField(
        help_text='Object size in bytes.',
    )
    s3_key = models.CharField(
        max_length=512,
        unique=True,
        help_text='Object key in the S3 bucket.',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        help_text='Timestamp of the file creation.',
    )

    class Meta:
        db_table = 'bublik_chat_file'
        ordering: ClassVar[list] = ['-created']

    def __repr__(self):
        return (
            f'ChatFile(id={self.id!r}, thread={self.thread_id!r}, '
            f'filename={self.filename!r}, size={self.size!r})'
        )


@receiver(pre_delete, sender=ChatThread, dispatch_uid='chat_file_s3_cleanup')
def _delete_thread_files_from_s3(sender, instance, **kwargs):
    """Best-effort S3 cleanup when a thread is deleted.

    ``pre_delete`` (not ``post_delete``) so the ChatFile rows still exist and
    threads without files skip the S3 round-trip entirely. Failures are logged
    and swallowed: object storage being down must not block thread deletion
    (operators on real S3 can use a lifecycle rule on the ``chat/`` prefix
    as a safety net).
    """
    if not instance.files.exists():
        return
    # Lazy: keep boto3 out of the model-import path (app registry load).
    from bublik.core import s3  # noqa: PLC0415

    try:
        s3.delete_prefix(f'chat/{instance.pk}/')
    except Exception:
        logger.warning(
            'failed to delete S3 objects for chat thread %s',
            instance.pk,
            exc_info=True,
        )
