FROM python:3.10 AS base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV PATH="/app/te/build/inst/default/bin:$PATH"

WORKDIR /app

RUN apt update && apt install \
gettext \
python3-celery \
openssl \
rsync \
flex \
bison \
ninja-build \
libjansson-dev \
libjansson-doc \
libjansson4 \
libpopt-dev \
libpcre3-dev \
pixz \
libxml-parser-perl \
build-essential -y && \
cpan JSON

RUN pip install --upgrade pip && pip install meson watchfiles
RUN mkdir bublik
COPY ./bublik/requirements.txt bublik
RUN pip install -r /app/bublik/requirements.txt

WORKDIR /app/te

COPY ../test-environment .
RUN ./dispatcher.sh -q --conf-builder=builder.conf.tools --no-run

FROM base AS runner

WORKDIR /app

COPY ../bublik bublik
COPY ../bublik-conf bublik-conf
RUN rm -rf /app/bublik/logs
RUN mkdir -p /app/bublik/logs

WORKDIR /app/bublik

ENTRYPOINT ["sh", "entrypoint.sh"]