[tool.ruff]
line-length = 96
target-version = 'py38'

[tool.ruff.lint]
select = [
    # pyflakes
    'F',
    # pycodestyle errors
    'E',
    # pycodestyle warnings
    'W',
    # mccabe
    'C90',
    # isort
    'I',
    # pep8-naming
    'N',
    # pyupgrade
    'UP',
    # flake8-2020
    'YTT',
    # flake8-bugbear
    'B',
    # flake8-builtins
    'A',
    # flake8-commas
    'COM',
    # flake8-comprehensions
    'C4',
    # flake8-debugger
    'T10',
    # flake8-django
    'DJ',
    # flake8-errmsg
    'EM',
    # flake8-executable
    'EXE',
    # flake8-future-annotations
    'FA',
    # flake8-implicit-str-concat
    'ISC',
    # flake8-import-conventions
    'ICN',
    # flake8-pie
    'PIE',
    # flake8-print
    'T20',
    # flake8-pyi
    'PYI',
    # flake8-pytest-style
    'PT',
    # flake8-quotes
    'Q',
    # flake8-raise
    'RSE',
    # flake8-return
    'RET',
    # flake8-simplify
    'SIM',
    # flake8-tidy-imports
    'TID',
    # flake8-type-checking
    'TCH',
    # flake8-gettext
    'INT',
    # eradicate
    'ERA',
    # pygrep-hooks
    'PGH',
    # Pylint
    'PL',
    # flynt
    'FLY',
    # NumPy-specific rules
    'NPY',
    # Ruff-specific rules
    'RUF',
]
ignore = [
    # overwriting some variables (seems to be usefull in some cases)
    'PLW2901',
]
exclude = [
    '.env',
    '.git',
    '__pycache__',
    'conf',
    'doc',
    'logs',
    'tests',
    'migrations',
]

[tool.ruff.lint.per-file-ignores]
'bublik/settings.py' = [
    # There is an import of per_conf that can't be moved to the top of the file
    'E402',
    'I001',
]
'bublik/core/testing_coverage.py' = [
    # generate_pdf() is too complex (23 > 16)
    'C901',
]
'bublik/data/*' = [
    # In order to keep the structure of DB the same
    'A003',
    # Keep the null=True for string-based fields
    'DJ001',
    # Use __repr__ instead of __str__
    'DJ008',
]
'bublik/interfaces/*' = [
    # In order to keep the structure of UI the same
    'A',
]
'bublik/interfaces/api_v2/history.py' = [
    # get_queryset() is too complex (19 > 16)
    'C901',
]
'bublik/interfaces/apps.py' = [
    'F401',
    'PLC0415',
]
'bublik/interfaces/management/commands/meta_categorization.py' = [
    # __resolve_mapping() is too complex (18 > 16)
    'C901',
]
'cgi/*' = [
    # print is used in cgi/
    'T201'
]
'cgi/show.py' = [
    # try_process_archive() is too complex (23 > 16)
    'C901',
]

[tool.ruff.lint.flake8-quotes]
avoid-escape = false
inline-quotes = 'single'
docstring-quotes = 'single'
multiline-quotes = 'single'

[tool.ruff.lint.mccabe]
max-complexity = 16

[tool.ruff.lint.isort]
force-sort-within-sections = true
split-on-trailing-comma = true
lines-after-imports = 2

[tool.ruff.lint.pylint]
max-args = 8
max-branches = 30
max-statements = 100
max-returns = 7

[tool.black]
line-length = 96
target-version = ['py38']
skip-string-normalization = true
