# Generated by Django 5.1.7 on 2025-06-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='config',
            name='project',
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={'name': 'PROJECT', 'type': 'label'},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='config',
                to='data.meta',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('type', 'name', 'project', 'version')},
        ),
    ]
