# Generated by Django 5.1.7 on 2025-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatest',
            name='updated',
            field=models.DateTimeField(
                auto_now_add=True, help_text='Timestamp of the connection creation.'
            ),
        ),
    ]
