# Generated by Django 5.1.7 on 2025-07-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_metatest_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatest',
            name='serial',
            field=models.IntegerField(
                help_text='The serial number is used to determine the order of comments.'
            ),
        ),
    ]
