# Generated by Django 5.1.7 on 2025-06-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_config_unique_together_config_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatest',
            name='meta',
            field=models.ForeignKey(
                help_text='A metadata identifier.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='meta_metatests',
                to='data.meta',
            ),
        ),
    ]
