# Generated by Django 5.1.7 on 2025-06-20 12:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_project_field(apps, schema_editor):
    Meta = apps.get_model('data', 'Meta')
    MetaTest = apps.get_model('data', 'MetaTest')
    if not MetaTest.objects.exists():
        return
    current_project = Meta.objects.get(type='label', name='PROJECT')
    MetaTest.objects.filter(project__isnull=True).update(project=current_project)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_alter_metatest_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="metatest",
            name="project",
            field=models.ForeignKey(
                limit_choices_to={"name": "PROJECT", "type": "label"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_metatests",
                to="data.meta",
            ),
        ),
        migrations.RunPython(backfill_project_field, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="metatest",
            name="project",
            field=models.ForeignKey(
                limit_choices_to={"name": "PROJECT", "type": "label"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_metatests",
                to="data.meta",
            ),
        ),
    ]
