# Generated by Django 5.1.7 on 2025-07-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_metatest_serial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metatest',
            unique_together={('test', 'meta')},
        ),
    ]
