# Generated by Django 5.1.7 on 2025-07-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_metatest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(help_text='The project name.', max_length=64, unique=True),
                ),
            ],
            options={
                'db_table': 'bublik_project',
            },
        ),
        migrations.AlterField(
            model_name='metacategory',
            name='name',
            field=models.CharField(help_text='Name of the category.', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='metatest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='config',
            name='project',
            field=models.ForeignKey(
                help_text='The project identifier.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='data.project',
            ),
        ),
        migrations.AddField(
            model_name='metacategory',
            name='project',
            field=models.ForeignKey(
                help_text='The project identifier.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='data.project',
            ),
        ),
        migrations.AddField(
            model_name='metatest',
            name='project',
            field=models.ForeignKey(
                help_text='The project identifier.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='data.project',
            ),
        ),
        migrations.AddField(
            model_name='testiterationresult',
            name='project',
            field=models.ForeignKey(
                help_text='The project identifier.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='data.project',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('type', 'name', 'project', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='metacategory',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='metatest',
            unique_together={('test', 'meta', 'project')},
        ),
    ]
