# Generated by Django 5.1.7 on 2025-08-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_project_alter_metacategory_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('project', 'type', 'name'),
                name='uniq_active_per_group',
            ),
        ),
    ]
