# Generated by Django 5.1.10 on 2025-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_project_alter_metacategory_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('project', 'content'), ('type', 'name', 'project', 'version')},
        ),
    ]
