# Generated by Django 5.1.10 on 2025-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_config_uniq_active_per_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, help_text='Timestamp of the config creation.'
            ),
        ),
    ]
