# Generated by Django 5.1.10 on 2025-08-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_config_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='version',
            field=models.IntegerField(help_text='Configuration version.'),
        ),
    ]
