# Generated by Django 5.1.7 on 2025-08-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_config_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='config',
            name='version',
            field=models.IntegerField(help_text='Configuration version.'),
        ),
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(
                fields=('type', 'name', 'project', 'version'), name='uniq_version_per_group'
            ),
        ),
    ]
