# Generated by Django 5.1.7 on 2025-08-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_config_unique_together_alter_config_version_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(
                fields=('type', 'name', 'project', 'content'), name='uniq_content_per_group'
            ),
        ),
    ]
