# Generated by Django 5.2.8 on 2025-11-20 17:52

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def assign_project_from_run(apps, schema_editor):
    TestIterationResult = apps.get_model('data', 'TestIterationResult')

    without_project_runs = TestIterationResult.objects.filter(
        test_run__isnull=True,
        project__isnull=True,
    )
    if without_project_runs.exists():
        without_project_run_ids = list(without_project_runs.values_list('id', flat=True))
        raise RuntimeError(
            f'The following runs are not linked to a project: {without_project_run_ids}. '
            'They need to be re-imported or deleted.'
        )

    TestIterationResult.objects.filter(project__isnull=True).update(
        project=Subquery(
            TestIterationResult.objects.filter(pk=OuterRef('pk')).values('test_run__project')[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_config_uniq_content_per_group'),
    ]

    operations = [
        migrations.RunPython(
            assign_project_from_run,
            reverse_code=django.db.migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='testiterationresult',
            name='project',
            field=models.ForeignKey(
                help_text='The project identifier.',
                on_delete=django.db.models.deletion.CASCADE,
                to='data.project',
            ),
        ),
    ]