# Generated by Django 5.2.13 on 2026-03-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_fix_iterations_project_nonnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('importruns', 'Importruns'),
                            ('meta_categorization', 'Meta Categorization'),
                        ],
                        help_text='The name of the job.',
                        max_length=64,
                    ),
                ),
                (
                    'started_at',
                    models.DateTimeField(
                        help_text='Timestamp when the job started.', null=True
                    ),
                ),
                (
                    'finished_at',
                    models.DateTimeField(
                        help_text='Timestamp when the job finished.', null=True
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_job',
            },
        ),
        migrations.CreateModel(
            name='JobTaskExecution',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(
                        help_text='The job identifier.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='data.job',
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_jobtaskexecution',
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'task_id',
                    models.UUIDField(db_index=True, help_text='Celery task UUID.', unique=True),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('RECEIVED', 'Received'),
                            ('RUNNING', 'Running'),
                            ('SUCCESS', 'Success'),
                            ('FAILURE', 'Failure'),
                        ],
                        db_index=True,
                        help_text='Current execution state of the task.',
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    'started_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the task started execution.',
                        null=True,
                    ),
                ),
                (
                    'finished_at',
                    models.DateTimeField(
                        blank=True, help_text='Timestamp when the task finished.', null=True
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_taskexecution',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                (
                    'job_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='data.job',
                    ),
                ),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'bublik_importjob',
            },
            bases=('data.job',),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='job_task_execution',
            field=models.ForeignKey(
                help_text='The job-task combination this event belongs to.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='data.jobtaskexecution',
            ),
        ),
        migrations.AddField(
            model_name='jobtaskexecution',
            name='task_execution',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='data.taskexecution'
            ),
        ),
        migrations.CreateModel(
            name='JobTaskExecutionResult',
            fields=[
                (
                    'jobtaskexecution_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='data.jobtaskexecution',
                    ),
                ),
                ('url', models.TextField(help_text='The run source URL.')),
                (
                    'run',
                    models.ForeignKey(
                        help_text='The run identifier.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='data.testiterationresult',
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_jobtaskexecutionresult',
            },
            bases=('data.jobtaskexecution',),
        ),
        migrations.AddConstraint(
            model_name='jobtaskexecution',
            constraint=models.UniqueConstraint(
                condition=models.Q(('task_execution__isnull', True)),
                fields=('job',),
                name='unique_null_task_execution_per_job',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='jobtaskexecution',
            unique_together={('job', 'task_execution')},
        ),
    ]
