# Generated by Django 5.2.14 on 2026-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_job_jobtaskexecution_taskexecution_importjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testiterationresult',
            name='exec_seqno',
            field=models.IntegerField(
                db_index=True,
                help_text='The execution sequence number (the actual test ID) which is generated during the testing.',
                null=True,
            ),
        ),
    ]
