# Generated by Django 5.2.14 on 2026-06-19 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_testiterationresult_exec_seqno'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueExt',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'key',
                    models.CharField(
                        help_text='External bug reference in ref://TRACKER/KEY form.',
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        help_text='Cached external status. Populated by the connector.',
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True,
                        help_text='Cached external summary. Populated by the connector.',
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    'synced_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Last successful sync with the tracker.',
                        null=True,
                    ),
                ),
                (
                    'raw',
                    models.JSONField(
                        blank=True, help_text='Optional raw tracker payload cache.', null=True
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_issue_ext',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(help_text='Internal label.', max_length=512)),
                (
                    'description',
                    models.TextField(blank=True, help_text='Internal notes.', null=True),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[('open', 'Open'), ('closed', 'Closed')],
                        default='open',
                        help_text='Bublik view of whether the bug is still active.',
                        max_length=16,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'closed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'issue_ext',
                    models.OneToOneField(
                        blank=True,
                        help_text='1:1 link to the external cache, or null for internal-only.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='issue',
                        to='data.issueext',
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_issue',
            },
        ),
        migrations.CreateModel(
            name='IssueRule',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('product-defect', 'Product Defect'),
                            ('test-bug', 'Test Bug'),
                            ('env', 'Env'),
                            ('known-issue', 'Known Issue'),
                            ('flaky', 'Flaky'),
                            ('to-investigate', 'To Investigate'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'expected',
                    models.BooleanField(
                        help_text='Whether matches suppress the unexpected count.'
                    ),
                ),
                (
                    'active',
                    models.BooleanField(
                        default=True, help_text='Whether it applies to future imports.'
                    ),
                ),
                ('match_parameters', models.BooleanField(default=True)),
                ('match_verdicts', models.BooleanField(default=True)),
                ('match_important_tags', models.BooleanField(default=True)),
                ('match_all_tags', models.BooleanField(default=False)),
                (
                    'parameters',
                    models.JSONField(
                        blank=True, default=dict, help_text='Captured {name: value}.'
                    ),
                ),
                (
                    'verdicts',
                    models.JSONField(
                        blank=True, default=list, help_text='Captured verdict strings.'
                    ),
                ),
                (
                    'tags',
                    models.JSONField(
                        blank=True, default=list, help_text='Captured tag strings.'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'deactivated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'issue',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rules',
                        to='data.issue',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='issue_rules',
                        to='data.project',
                    ),
                ),
                (
                    'test',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='issue_rules',
                        to='data.test',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_issuerule',
            },
        ),
        migrations.CreateModel(
            name='ResultClassification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'origin',
                    models.CharField(
                        choices=[
                            ('import', 'Import'),
                            ('manual_apply', 'Manual Apply'),
                            ('manual_oneoff', 'Manual Oneoff'),
                        ],
                        max_length=16,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'result',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='classifications',
                        to='data.testiterationresult',
                    ),
                ),
                (
                    'rule',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stamps',
                        to='data.issuerule',
                    ),
                ),
            ],
            options={
                'db_table': 'bublik_resultclassification',
                'unique_together': {('result', 'rule')},
            },
        ),
    ]
