# Generated by Django 5.2.14 on 2026-07-20 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_testiterationresult_exec_seqno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Thread identifier (client-supplied).', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Human-readable thread title.', max_length=255)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether the thread is archived (hidden from the default list).')),
                ('messages', models.JSONField(default=list, help_text='The conversation messages (UIMessage[]).')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the thread creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last thread update.')),
                ('user', models.ForeignKey(help_text='The user who owns the thread.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bublik_chat_thread',
                'ordering': ['-updated'],
            },
        ),
    ]
