# Generated by Django 5.2.14 on 2026-07-20 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_testiterationresult_exec_seqno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Thread identifier (client-supplied).', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Human-readable thread title.', max_length=255)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether the thread is archived (hidden from the default list).')),
                ('messages', models.JSONField(default=list, help_text='The conversation messages (UIMessage[]).')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the thread creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last thread update.')),
                ('user', models.ForeignKey(help_text='The user who owns the thread.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bublik_ai_chat_thread',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='AiChatFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='File identifier (used in the download URL).', primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Download filename.', max_length=255)),
                ('content_type', models.CharField(help_text='MIME type served on download.', max_length=127)),
                ('size', models.PositiveIntegerField(help_text='Object size in bytes.')),
                ('storage_key', models.CharField(help_text='Key in the chat file store (S3 object key, or path on disk).', max_length=512, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the file creation.')),
                ('thread', models.ForeignKey(help_text='The chat thread the file was generated in.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data.aichatthread')),
            ],
            options={
                'db_table': 'bublik_ai_chat_file',
                'ordering': ['-created'],
            },
        ),
    ]
