# Generated by Django 5.2.14 on 2026-07-20 21:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_chatthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='File identifier (used in the download URL).', primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Download filename.', max_length=255)),
                ('content_type', models.CharField(help_text='MIME type served on download.', max_length=127)),
                ('size', models.PositiveIntegerField(help_text='Object size in bytes.')),
                ('s3_key', models.CharField(help_text='Object key in the S3 bucket.', max_length=512, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the file creation.')),
                ('thread', models.ForeignKey(help_text='The chat thread the file was generated in.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data.chatthread')),
            ],
            options={
                'db_table': 'bublik_chat_file',
                'ordering': ['-created'],
            },
        ),
    ]
