# Generated by Django 5.2.16 on 2026-09-13 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_ai_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal label.', max_length=512)),
                ('description', models.TextField(blank=True, help_text='Internal notes.', null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Bublik view of whether the bug is still active.', max_length=16)),
                ('bug_key', models.CharField(blank=True, help_text='External bug reference in ref://TRACKER/KEY form, or null if unlinked.', max_length=256, null=True, validators=[django.core.validators.RegexValidator(message='Bug key must be in ref://TRACKER/KEY form.', regex='^ref://([^/\\s]+)/([\\w\\-/:]+)$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='data.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bublik_issue',
            },
        ),
        migrations.CreateModel(
            name='IssueRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product-defect', 'Product Defect'), ('test-bug', 'Test Bug'), ('env', 'Env'), ('known-issue', 'Known Issue'), ('flaky', 'Flaky'), ('to-investigate', 'To Investigate')], max_length=32)),
                ('expected', models.BooleanField(blank=True, help_text='Disposition: True=expected (suppresses), False=unexpected, None=none (marker only).', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether it applies to future imports.')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Captured {name: value} subset, matched against the result. Empty = parameters ignored.')),
                ('verdicts', models.JSONField(blank=True, default=list, help_text='Captured verdict strings, matched as a subset. Empty = ignored.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Captured tag strings (important+relevant), matched as a subset. Empty = no tag gate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='data.issue')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_rules', to='data.test')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bublik_issuerule',
            },
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('import', 'Import'), ('manual_persistent', 'Manual Persistent'), ('manual_oneoff', 'Manual Oneoff')], help_text='How this result was classified.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue_rule', models.ForeignKey(help_text='The issue rule identifier.', on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='data.issuerule')),
                ('result', models.ForeignKey(help_text='The test iteration result identifier.', on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='data.testiterationresult')),
            ],
            options={
                'db_table': 'bublik_ruleresult',
            },
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='issue_unique_project_title'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('project', 'bug_key'), name='issue_unique_project_bug_key'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('bug_key__isnull', True), ('bug_key__regex', '^ref://([^/\\s]+)/([\\w\\-/:]+)$'), _connector='OR'), name='issue_bug_key_format'),
        ),
        migrations.AddConstraint(
            model_name='ruleresult',
            constraint=models.UniqueConstraint(fields=('result', 'issue_rule'), name='ruleresult_unique_result_rule'),
        ),
    ]
