# Generated by Django 5.2.16 on 2026-09-29 19:07

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_ai_chat'),
    ]

    operations = [
        # existing users get the date user registration appeared in Bublik,
        # the earliest date they could have joined, since the real one is unknown
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
