# Generated by Django 5.2.16 on 2026-09-28 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_ai_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.ForeignKey(help_text='The user who created the configuration object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
    ]
