# Generated by Django 5.2.14 on 2026-09-17 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_ai_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name, e.g. the client the token is configured in.",
                        max_length=64,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="Visible handle: the bpat_ marker plus the first few characters.",
                        max_length=16,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 of the token. The token itself is never stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the token creation."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token stops working. NULL means it never expires.",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the token authenticated a request, to the minute.",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token was revoked. NULL means it is still valid.",
                        null=True,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who revoked the token -- its owner, or an admin.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user the token acts as.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bublik_user_token",
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("user", "name"),
                        name="uniq_active_token_name_per_user",
                    )
                ],
            },
        ),
    ]
