# Generated by Django 5.2.16 on 2026-09-29 19:15

from django.db import migrations, models


def set_status_from_is_active(apps, schema_editor):
    User = apps.get_model('data', 'User')
    User.objects.filter(is_active=True).update(status='active')
    User.objects.filter(is_active=False).update(status='deactivated')


def set_is_active_from_status(apps, schema_editor):
    User = apps.get_model('data', 'User')
    User.objects.exclude(status='active').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='pending', max_length=16, verbose_name='User status'),
        ),
        migrations.RunPython(set_status_from_is_active, set_is_active_from_status),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
