# Generated by Django 5.2.14 on 2026-09-22 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0014_user_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMcpServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name shown in settings.",
                        max_length=64,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        help_text="Derived from the name; prefixes every tool name the server exposes.",
                        max_length=32,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Streamable HTTP endpoint of the server.",
                        max_length=2048,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled servers are kept but not attached to chat runs.",
                    ),
                ),
                (
                    "headers_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fernet token over the JSON header mapping. Empty means no headers.",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The only user whose chat runs see this server.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bublik_user_mcp_server",
                "ordering": ["name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "slug"), name="uniq_mcp_server_slug_per_user"
                    )
                ],
            },
        ),
    ]
