# Generated by Django 5.2.14 on 2026-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_chatfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='context_state',
            field=models.JSONField(default=dict, help_text='Server-managed context bookkeeping: last known context token occupancy and the cached compaction summary (see bublik.ai.compaction). Never written by the client.'),
        ),
    ]
