# Generated by Django 5.2.11 on 2026-03-24 23:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'event_uuid',
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('event_name', models.CharField(blank=True, default='', max_length=128)),
                (
                    'path',
                    models.CharField(blank=True, db_index=True, default='', max_length=512),
                ),
                (
                    'anon_id',
                    models.CharField(blank=True, db_index=True, default='', max_length=128),
                ),
                ('session_id', models.CharField(blank=True, default='', max_length=128)),
                ('browser_name', models.CharField(blank=True, default='', max_length=128)),
                ('browser_version', models.CharField(blank=True, default='', max_length=64)),
                ('os_name', models.CharField(blank=True, default='', max_length=128)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                (
                    'app_version',
                    models.CharField(blank=True, db_index=True, default='', max_length=64),
                ),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [
                    models.Index(
                        fields=['event_type', 'occurred_at'],
                        name='analytics_a_event_t_69a889_idx',
                    ),
                    models.Index(
                        fields=['event_name', 'occurred_at'],
                        name='analytics_a_event_n_aeeca0_idx',
                    ),
                    models.Index(
                        fields=['path', 'occurred_at'],
                        name='analytics_a_path_2e7306_idx',
                    ),
                ],
            },
        ),
    ]
