#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2016-2023 OKTET Labs Ltd. All rights reserved.

set -e

CONFIG_DIR="$(readlink -f $(dirname "$0")/../bublik)"

if [ -e "${CONFIG_DIR}/general.conf" ] ; then
  set -a
  . "${CONFIG_DIR}/general.conf"
  set +a
  export PATH=$PATH:$TE_BASE
fi

source "${SCRIPTS_DIR}/lib"
