#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2016-2023 OKTET Labs Ltd. All rights reserved.

source "$(dirname $0)/exports"

set -e

pushd "${BUBLIK_SRC}" >/dev/null
source "${ENV_DIR}/bin/activate"
[[ $# -eq 0 ]] || ./manage.py "$@"
popd >/dev/null
