#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2016-2023 OKTET Labs Ltd. All rights reserved.
#
# Prepare virtual env to be possible run django commands.
#
source "$(dirname $0)/exports"

set -e

pushd "${BUBLIK_SRC}"

rm -rf "${ENV_DIR}"
virtualenv --python=python3 "${ENV_DIR}"
source "${ENV_DIR}/bin/activate"
python3 -m pip install -r requirements.txt
deactivate
popd
