#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2016-2023 OKTET Labs Ltd. All rights reserved.

status=0

# Pytype checks and infers types for your Python code - without requiring type annotations.
# Pytype is a static analyzer; it does not execute the code it runs on.
# https://github.com/google/pytype.
#
pip show -q pytype && pytype $@
status=$(( $status | $? ))

# Ruff checks Python code style, imports, complexity, and common lint issues.
#
pip show -q ruff && ruff check $@
status=$(( $status | $? ))

# Pyanalize status.
#
exit $status
