#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2016-2023 OKTET Labs Ltd. All rights reserved.

source "$(dirname $0)/manage"

gunicorn \
  --limit-request-line 0 \
  --chdir "${BUBLIK_SRC}" \
  --bind "${BUBLIK_BIND_GUNICORN}" \
  --workers "${BUBLIK_WORKERS}" \
  --timeout "${BUBLIK_TIMEOUT}" \
  --graceful-timeout "${BUBLIK_GRACEFUL_TIMEOUT}" \
  --log-file "${BUBLIK_LOG}" \
  --access-logfile "${BUBLIK_ACCESS_LOG}" \
  --log-level info \
  --worker-tmp-dir "${TMPDIR}" \
  --pid "${BUBLIK_GUNICORN_PID_PATH}" \
  --name "${BUBLIK_WEB_NAME}" \
    bublik.wsgi:application
