#!/bin/bash -e
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2016-2023 OKTET Labs Ltd. All rights reserved.

source "$(dirname $0)/exports"

${SCRIPTS_DIR}/manage graph_models -g -o bublik/data/schema.png data
